---
title: "Natural Disaster Events Analysis"
author: "Ziaul Hoque"
format: html
editor: visual
---

## Natural Disaster Events-Analysis

### Approach

In this assignment, I selected a dataset from kaggle, regarding an analytical investigation of worldwide natural disaster occurences documented between 2023 and 2025. This dataset contains important characteristics such the type of disaster, location, degree of severity, number of victims, financial losses, and emergency response timings are all captured here and also gives an opportunity to working with enormous numerical data.

My goal is to work with this data and get insights information through data driven approach and analyze incidents in different locations worldwide and get more information & visualize data to improve emergency response plans, risk mitigation techniques and disaster preparedness. So data driven insights are essential for identifying susceptible areas and allocating resources as emergency needed.

### Data Sources

<https://github.com/CandySoftInc/DATA607-Assignment1-Natural-Disaster-Events/blob/main/synthetic_disaster_events_2025.csv>

### Research Question

How we can improve more awareness to people before any natural disaster happens and how we can prevent loss or degree of severity, number of victims through this analysis?
